export const GET_ALL_HOT_DEALS_REQUEST = "GET_ALL_HOT_DEALS_REQUEST";
export const GET_ALL_HOT_DEALS_SUCCESS = "GET_ALL_HOT_DEALS_SUCCESS";
export const GET_ALL_HOT_DEALS_FAILURE = "GET_ALL_HOT_DEALS_FAILURE";

export const ADD_HOT_DEAL_REQUEST = "ADD_HOT_DEAL_REQUEST";
export const ADD_HOT_DEAL_SUCCESS = "ADD_HOT_DEAL_SUCCESS";
export const ADD_HOT_DEAL_FAILURE = "ADD_HOT_DEAL_FAILURE";

export const GET_HOT_DEAL_BY_ID_REQUEST = "GET_HOT_DEAL_BY_ID_REQUEST";
export const GET_HOT_DEAL_BY_ID_SUCCESS = "GET_HOT_DEAL_BY_ID_SUCCESS";
export const GET_HOT_DEAL_BY_ID_FAILURE = "GET_HOT_DEAL_BY_ID_FAILURE";

export const UPDATE_HOT_DEAL_REQUEST = "UPDATE_HOT_DEAL_REQUEST";
export const UPDATE_HOT_DEAL_SUCCESS = "UPDATE_HOT_DEAL_SUCCESS";
export const UPDATE_HOT_DEAL_FAILURE = "UPDATE_HOT_DEAL_FAILURE";

export const DELETE_HOT_DEAL_REQUEST = "DELETE_HOT_DEAL_REQUEST";
export const DELETE_HOT_DEAL_SUCCESS = "DELETE_HOT_DEAL_SUCCESS";
export const DELETE_HOT_DEAL_FAILURE = "DELETE_HOT_DEAL_FAILURE";
