export const GET_ALL_FLASH_DEALS_REQUEST = "GET_ALL_FLASH_DEALS_REQUEST";
export const GET_ALL_FLASH_DEALS_SUCCESS = "GET_ALL_FLASH_DEALS_SUCCESS";
export const GET_ALL_FLASH_DEALS_FAILURE = "GET_ALL_FLASH_DEALS_FAILURE";

export const UPDATE_FLASH_DEAL_REQUEST = "UPDATE_FLASH_DEAL_REQUEST";
export const UPDATE_FLASH_DEAL_SUCCESS = "UPDATE_FLASH_DEAL_SUCCESS";
export const UPDATE_FLASH_DEAL_FAILURE = "UPDATE_FLASH_DEAL_FAILURE";
