export const GET_ALL_CODE_REQUEST = "GET_ALL_CODE_REQUEST";
export const GET_ALL_CODE_SUCCESS = "GET_ALL_CODE_SUCCESS";
export const GET_ALL_CODE_FAILURE = "GET_ALL_CODE_FAILURE";

export const ADD_CODE_REQUEST = "ADD_CODE_REQUEST";
export const ADD_CODE_SUCCESS = "ADD_CODE_SUCCESS";
export const ADD_CODE_FAILURE = "ADD_CODE_FAILURE";

export const UPDATE_CODE_REQUEST = "UPDATE_CODE_REQUEST";
export const UPDATE_CODE_SUCCESS = "UPDATE_CODE_SUCCESS";
export const UPDATE_CODE_FAILURE = "UPDATE_CODE_FAILURE";

export const GET_CODE_REQUEST = "GET_CODE_REQUEST";
export const GET_CODE_SUCCESS = "GET_CODE_SUCCESS";
export const GET_CODE_FAILURE = "GET_CODE_FAILURE";

export const DELETE_CODE_REQUEST = "DELETE_CODE_REQUEST";
export const DELETE_CODE_SUCCESS = "DELETE_CODE_SUCCESS";
export const DELETE_CODE_FAILURE = "DELETE_CODE_FAILURE";
